# Generated by Django 6.1.1 on 2026-09-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
