# Generated by Django 6.1.1 on 2026-09-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_recipes', '0002_alter_recipe_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
